---
spec/spec_helper.rb:
  mock_with: ':rspec'

appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.gitignore:
  paths:
    - vendor/

Rakefile:
  extras:
    - |
      Rake::Task['rubocop'].clear
      RuboCop::RakeTask.new(:rubocop) do |task|
        task.options = [
          '--config', '.rubocop.yml'
        ]
      end

